import { AppTheme } from '../types';

// ─── Старшие (8-11 класс) ────────────────────────────────────────

const csgoTheme: AppTheme = {
  id: 'csgo',
  name: 'CS:GO',
  emoji: '🔫',
  ageGroup: 'senior',
  characters: [
    {
      id: 'csgo-ct',
      name: 'Контр-террорист',
      emoji: '🛡️',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#3B6EA5',
        secondaryColor: '#2A4A6B',
        accentColor: '#1A2E42',
        scale: 1.0,
        headShape: 'sphere',
        hasWeapon: 'shield',
      },
      mascotEmojis: { sick: '💀', sad: '😰', neutral: '🛡️', happy: '😎', thriving: '🏆' },
    },
    {
      id: 'csgo-t',
      name: 'Террорист',
      emoji: '💣',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#8B6914',
        secondaryColor: '#6B4E10',
        accentColor: '#3D2E0A',
        scale: 1.0,
        headShape: 'sphere',
        hasWeapon: 'sword',
      },
      mascotEmojis: { sick: '💀', sad: '😤', neutral: '💣', happy: '🔥', thriving: '⚡' },
    },
    {
      id: 'csgo-awp',
      name: 'AWPер',
      emoji: '🎯',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#2D5A27',
        secondaryColor: '#1E3D1A',
        accentColor: '#4A7A44',
        scale: 1.0,
        headShape: 'sphere',
        hasWeapon: 'staff',
      },
      mascotEmojis: { sick: '💀', sad: '😓', neutral: '🎯', happy: '🔫', thriving: '👑' },
    },
    {
      id: 'csgo-spec',
      name: 'Спецназ',
      emoji: '⚔️',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#1A1A1A',
        secondaryColor: '#333333',
        accentColor: '#E87B35',
        scale: 1.0,
        headShape: 'sphere',
        hasWeapon: 'sword',
      },
      mascotEmojis: { sick: '💀', sad: '😣', neutral: '⚔️', happy: '💪', thriving: '🦾' },
    },
  ],
  colors: {
    primary: '#E87B35',
    secondary: '#F5A623',
    accent: '#FF6B00',
    background: '#1A1A1A',
    surface: '#2A2A2A',
    text: '#F0E6D8',
    textSecondary: '#9A9080',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#E87B35', '#C75B20'],
    tabBar: '#1E1E1E',
    tabBarActive: '#F5A623',
    tabBarInactive: '#6B6358',
    card: '#2E2E2E',
    border: '#3D3830',
  },
};

const gotTheme: AppTheme = {
  id: 'got',
  name: 'Игра Престолов',
  emoji: '🐉',
  ageGroup: 'senior',
  characters: [
    {
      id: 'got-dragon',
      name: 'Дракон',
      emoji: '🐉',
      config3d: {
        bodyType: 'quadruped',
        primaryColor: '#8B0000',
        secondaryColor: '#2A0A0A',
        accentColor: '#FF4500',
        scale: 1.1,
        headShape: 'cone',
        hasWings: true,
        hasTail: true,
        hasHorns: true,
      },
      mascotEmojis: { sick: '🥀', sad: '😔', neutral: '🐉', happy: '🔥', thriving: '👑' },
    },
    {
      id: 'got-wolf',
      name: 'Волк',
      emoji: '🐺',
      config3d: {
        bodyType: 'quadruped',
        primaryColor: '#808080',
        secondaryColor: '#B0B0B0',
        accentColor: '#505050',
        scale: 1.0,
        headShape: 'sphere',
        hasTail: true,
      },
      mascotEmojis: { sick: '🤕', sad: '🌧️', neutral: '🐺', happy: '🌙', thriving: '❄️' },
    },
    {
      id: 'got-lion',
      name: 'Лев',
      emoji: '🦁',
      config3d: {
        bodyType: 'quadruped',
        primaryColor: '#C9A84C',
        secondaryColor: '#A08030',
        accentColor: '#8B6914',
        scale: 1.05,
        headShape: 'sphere',
        hasTail: true,
      },
      mascotEmojis: { sick: '😵', sad: '😠', neutral: '🦁', happy: '💰', thriving: '⚔️' },
    },
    {
      id: 'got-raven',
      name: 'Ворон',
      emoji: '🐦‍⬛',
      config3d: {
        bodyType: 'bird',
        primaryColor: '#1A1A2E',
        secondaryColor: '#2A2A3E',
        accentColor: '#4A4A5E',
        scale: 0.9,
        headShape: 'sphere',
        hasWings: true,
      },
      mascotEmojis: { sick: '💀', sad: '🌑', neutral: '🐦‍⬛', happy: '🔮', thriving: '👁️' },
    },
  ],
  colors: {
    primary: '#C9A84C',
    secondary: '#E8D282',
    accent: '#8B0000',
    background: '#121010',
    surface: '#1E1A18',
    text: '#F0E8D8',
    textSecondary: '#A09882',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#8B0000', '#C9A84C'],
    tabBar: '#161212',
    tabBarActive: '#C9A84C',
    tabBarInactive: '#6B6050',
    card: '#252020',
    border: '#3A3028',
  },
};

const twilightTheme: AppTheme = {
  id: 'twilight',
  name: 'Сумерки',
  emoji: '🧛',
  ageGroup: 'senior',
  characters: [
    {
      id: 'tw-vampire',
      name: 'Вампир',
      emoji: '🧛',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#E8E0F0',
        secondaryColor: '#1A1020',
        accentColor: '#8B0A1A',
        scale: 1.05,
        headShape: 'sphere',
        hasWeapon: 'staff',
      },
      mascotEmojis: { sick: '💀', sad: '🌑', neutral: '🧛', happy: '🩸', thriving: '⚡' },
    },
    {
      id: 'tw-werewolf',
      name: 'Оборотень',
      emoji: '🐺',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#6B4E3D',
        secondaryColor: '#4A3428',
        accentColor: '#8B6B50',
        scale: 1.1,
        headShape: 'sphere',
        hasWeapon: 'staff',
      },
      mascotEmojis: { sick: '🤒', sad: '😢', neutral: '🐺', happy: '🌕', thriving: '💪' },
    },
    {
      id: 'tw-shewolf',
      name: 'Волчица',
      emoji: '🌙',
      config3d: {
        bodyType: 'quadruped',
        primaryColor: '#A08878',
        secondaryColor: '#D0C0B0',
        accentColor: '#6B5548',
        scale: 0.95,
        headShape: 'sphere',
        hasTail: true,
      },
      mascotEmojis: { sick: '😷', sad: '😿', neutral: '🌙', happy: '✨', thriving: '🌟' },
    },
    {
      id: 'tw-mystic',
      name: 'Мистик',
      emoji: '🔮',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#6B2D5B',
        secondaryColor: '#3A1830',
        accentColor: '#A050A0',
        scale: 1.0,
        headShape: 'sphere',
        hasWeapon: 'staff',
      },
      mascotEmojis: { sick: '😵‍💫', sad: '😶‍🌫️', neutral: '🔮', happy: '🌌', thriving: '🌠' },
    },
  ],
  colors: {
    primary: '#8B0A1A',
    secondary: '#C0C0C0',
    accent: '#6B2D5B',
    background: '#0D0D12',
    surface: '#1A1820',
    text: '#E8E0F0',
    textSecondary: '#8A82A0',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#4A0E2C', '#8B0A1A'],
    tabBar: '#111018',
    tabBarActive: '#C0C0C0',
    tabBarInactive: '#5A5270',
    card: '#201C28',
    border: '#302838',
  },
};

const animeTheme: AppTheme = {
  id: 'anime',
  name: 'Аниме',
  emoji: '⛩️',
  ageGroup: 'senior',
  characters: [
    {
      id: 'anime-naruto',
      name: 'Наруто',
      emoji: '🍥',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#FF8C00',
        secondaryColor: '#1E3A5F',
        accentColor: '#FFD700',
        scale: 1.0,
        headShape: 'sphere',
        hasWeapon: 'sword',
      },
      mascotEmojis: { sick: '😵', sad: '😤', neutral: '🍥', happy: '💪', thriving: '🌀' },
    },
    {
      id: 'anime-ninja',
      name: 'Ниндзя',
      emoji: '🥷',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#1A1A2E',
        secondaryColor: '#2A2A3E',
        accentColor: '#505070',
        scale: 1.0,
        headShape: 'cube',
        hasWeapon: 'sword',
      },
      mascotEmojis: { sick: '🤕', sad: '😶', neutral: '🥷', happy: '⚡', thriving: '🔥' },
    },
    {
      id: 'anime-sakura',
      name: 'Сакура',
      emoji: '🌸',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#FFB7C5',
        secondaryColor: '#FF6B9D',
        accentColor: '#C850C0',
        scale: 0.95,
        headShape: 'sphere',
        hasWeapon: 'staff',
      },
      mascotEmojis: { sick: '🥀', sad: '😢', neutral: '🌸', happy: '💮', thriving: '✨' },
    },
    {
      id: 'anime-sensei',
      name: 'Сенсей',
      emoji: '📖',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#C0C0C0',
        secondaryColor: '#2A4A2A',
        accentColor: '#7B2FBE',
        scale: 1.05,
        headShape: 'sphere',
        hasWeapon: 'staff',
      },
      mascotEmojis: { sick: '😷', sad: '😑', neutral: '📖', happy: '🎓', thriving: '👑' },
    },
  ],
  colors: {
    primary: '#C850C0',
    secondary: '#FF6B9D',
    accent: '#7B2FBE',
    background: '#140818',
    surface: '#1E1025',
    text: '#F8E8FF',
    textSecondary: '#A888C0',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#7B2FBE', '#C850C0'],
    tabBar: '#180C20',
    tabBarActive: '#FF6B9D',
    tabBarInactive: '#6A4880',
    card: '#261830',
    border: '#382548',
  },
};

// ─── Младшие (5-7 класс) ─────────────────────────────────────────

const frozenTheme: AppTheme = {
  id: 'frozen',
  name: 'Холодное сердце',
  emoji: '❄️',
  ageGroup: 'junior',
  characters: [
    {
      id: 'fz-elsa',
      name: 'Эльза',
      emoji: '👸',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#A3D5F7',
        secondaryColor: '#5BA4CF',
        accentColor: '#C4A8FF',
        scale: 1.0,
        headShape: 'sphere',
        hasCrown: true,
      },
      mascotEmojis: { sick: '🥶', sad: '😢', neutral: '👸', happy: '❄️', thriving: '✨' },
    },
    {
      id: 'fz-olaf',
      name: 'Олаф',
      emoji: '⛄',
      config3d: {
        bodyType: 'snowman',
        primaryColor: '#F0F0FF',
        secondaryColor: '#8B6914',
        accentColor: '#FF6600',
        scale: 0.95,
        headShape: 'sphere',
      },
      mascotEmojis: { sick: '🫠', sad: '😥', neutral: '⛄', happy: '☀️', thriving: '🤗' },
    },
    {
      id: 'fz-anna',
      name: 'Анна',
      emoji: '👧',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#C75050',
        secondaryColor: '#2A5A2A',
        accentColor: '#FFD700',
        scale: 0.95,
        headShape: 'sphere',
        hasCrown: true,
      },
      mascotEmojis: { sick: '🤒', sad: '😟', neutral: '👧', happy: '💕', thriving: '🌸' },
    },
    {
      id: 'fz-sven',
      name: 'Свен',
      emoji: '🦌',
      config3d: {
        bodyType: 'quadruped',
        primaryColor: '#8B6914',
        secondaryColor: '#6B4E10',
        accentColor: '#A08030',
        scale: 1.0,
        headShape: 'sphere',
        hasHorns: true,
      },
      mascotEmojis: { sick: '🤕', sad: '😔', neutral: '🦌', happy: '🥕', thriving: '🎉' },
    },
  ],
  colors: {
    primary: '#5BA4CF',
    secondary: '#A3D5F7',
    accent: '#C4A8FF',
    background: '#E8F4FC',
    surface: '#FFFFFF',
    text: '#1A3A5C',
    textSecondary: '#6890B0',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#5BA4CF', '#A3D5F7'],
    tabBar: '#F0F8FF',
    tabBarActive: '#5BA4CF',
    tabBarInactive: '#98BEDD',
    card: '#FFFFFF',
    border: '#D0E8F8',
  },
};

const minionsTheme: AppTheme = {
  id: 'minions',
  name: 'Миньоны',
  emoji: '🍌',
  ageGroup: 'junior',
  characters: [
    {
      id: 'mn-bob',
      name: 'Боб',
      emoji: '🧸',
      config3d: {
        bodyType: 'blob',
        primaryColor: '#FFD02E',
        secondaryColor: '#3D5FA0',
        accentColor: '#1A1A2E',
        scale: 0.9,
        headShape: 'sphere',
      },
      mascotEmojis: { sick: '🤒', sad: '🥺', neutral: '🧸', happy: '😄', thriving: '🥳' },
    },
    {
      id: 'mn-kevin',
      name: 'Кевин',
      emoji: '🍌',
      config3d: {
        bodyType: 'blob',
        primaryColor: '#FFD02E',
        secondaryColor: '#3D5FA0',
        accentColor: '#1A1A2E',
        scale: 1.05,
        headShape: 'cylinder',
      },
      mascotEmojis: { sick: '😷', sad: '😣', neutral: '🍌', happy: '😁', thriving: '🦸' },
    },
    {
      id: 'mn-stuart',
      name: 'Стюарт',
      emoji: '🎸',
      config3d: {
        bodyType: 'blob',
        primaryColor: '#FFD02E',
        secondaryColor: '#3D5FA0',
        accentColor: '#1A1A2E',
        scale: 0.95,
        headShape: 'sphere',
        hasWeapon: 'guitar',
      },
      mascotEmojis: { sick: '🤕', sad: '😴', neutral: '🎸', happy: '🎶', thriving: '🤘' },
    },
    {
      id: 'mn-gru',
      name: 'Грю',
      emoji: '🦹',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#2A2A3C',
        secondaryColor: '#4A4A5C',
        accentColor: '#808090',
        scale: 1.1,
        headShape: 'sphere',
      },
      mascotEmojis: { sick: '😵', sad: '😤', neutral: '🦹', happy: '😏', thriving: '💎' },
    },
  ],
  colors: {
    primary: '#FFD02E',
    secondary: '#FEE680',
    accent: '#3D5FA0',
    background: '#FFF8E0',
    surface: '#FFFFFF',
    text: '#2A2A3C',
    textSecondary: '#7A7A90',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#FFD02E', '#FEB624'],
    tabBar: '#FFF8E8',
    tabBarActive: '#3D5FA0',
    tabBarInactive: '#B0B0C8',
    card: '#FFFFFF',
    border: '#F0E4C0',
  },
};

const clashRoyaleTheme: AppTheme = {
  id: 'clash',
  name: 'Clash Royale',
  emoji: '🏰',
  ageGroup: 'junior',
  characters: [
    {
      id: 'cr-king',
      name: 'Король',
      emoji: '👑',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#4A6FE0',
        secondaryColor: '#8B0000',
        accentColor: '#FFD700',
        scale: 1.05,
        headShape: 'sphere',
        hasCrown: true,
      },
      mascotEmojis: { sick: '😵', sad: '😠', neutral: '👑', happy: '😤', thriving: '🏆' },
    },
    {
      id: 'cr-princess',
      name: 'Принцесса',
      emoji: '🏹',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#FF69B4',
        secondaryColor: '#C850C0',
        accentColor: '#FFD700',
        scale: 0.9,
        headShape: 'sphere',
        hasWeapon: 'bow',
      },
      mascotEmojis: { sick: '🤕', sad: '😢', neutral: '🏹', happy: '🎯', thriving: '💫' },
    },
    {
      id: 'cr-knight',
      name: 'Рыцарь',
      emoji: '⚔️',
      config3d: {
        bodyType: 'humanoid',
        primaryColor: '#808080',
        secondaryColor: '#505050',
        accentColor: '#C0C0C0',
        scale: 1.0,
        headShape: 'cube',
        hasWeapon: 'sword',
      },
      mascotEmojis: { sick: '🩹', sad: '😔', neutral: '⚔️', happy: '🛡️', thriving: '💪' },
    },
    {
      id: 'cr-dragon',
      name: 'Дракон',
      emoji: '🐲',
      config3d: {
        bodyType: 'quadruped',
        primaryColor: '#9B59B6',
        secondaryColor: '#6B3A8A',
        accentColor: '#FF6B00',
        scale: 1.0,
        headShape: 'cone',
        hasWings: true,
        hasTail: true,
      },
      mascotEmojis: { sick: '😮‍💨', sad: '😕', neutral: '🐲', happy: '🔥', thriving: '⭐' },
    },
  ],
  colors: {
    primary: '#4A6FE0',
    secondary: '#7B9EF5',
    accent: '#9B59B6',
    background: '#0E1638',
    surface: '#182050',
    text: '#E8EEFF',
    textSecondary: '#8898CC',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#4A6FE0', '#9B59B6'],
    tabBar: '#121A40',
    tabBarActive: '#7B9EF5',
    tabBarInactive: '#4A5888',
    card: '#1E2860',
    border: '#283470',
  },
};

const pokemonTheme: AppTheme = {
  id: 'pokemon',
  name: 'Покемон',
  emoji: '⚡',
  ageGroup: 'junior',
  characters: [
    {
      id: 'pk-pikachu',
      name: 'Пикачу',
      emoji: '⚡',
      config3d: {
        bodyType: 'blob',
        primaryColor: '#FFD700',
        secondaryColor: '#CC8800',
        accentColor: '#FF0000',
        scale: 0.95,
        headShape: 'sphere',
        hasTail: true,
      },
      mascotEmojis: { sick: '😷', sad: '😢', neutral: '⚡', happy: '😊', thriving: '🌟' },
    },
    {
      id: 'pk-charmander',
      name: 'Чармандер',
      emoji: '🔥',
      config3d: {
        bodyType: 'blob',
        primaryColor: '#FF6B00',
        secondaryColor: '#FFD02E',
        accentColor: '#FF0000',
        scale: 0.95,
        headShape: 'sphere',
        hasTail: true,
      },
      mascotEmojis: { sick: '😮‍💨', sad: '😥', neutral: '🔥', happy: '😤', thriving: '🐉' },
    },
    {
      id: 'pk-squirtle',
      name: 'Сквиртл',
      emoji: '🐢',
      config3d: {
        bodyType: 'blob',
        primaryColor: '#5BA4CF',
        secondaryColor: '#A3D5F7',
        accentColor: '#8B6914',
        scale: 0.9,
        headShape: 'sphere',
        hasTail: true,
      },
      mascotEmojis: { sick: '🤒', sad: '😿', neutral: '🐢', happy: '💧', thriving: '🌊' },
    },
    {
      id: 'pk-bulbasaur',
      name: 'Бульбазавр',
      emoji: '🌿',
      config3d: {
        bodyType: 'quadruped',
        primaryColor: '#2D8B46',
        secondaryColor: '#48C964',
        accentColor: '#8B2252',
        scale: 0.95,
        headShape: 'sphere',
      },
      mascotEmojis: { sick: '🥀', sad: '😔', neutral: '🌿', happy: '🌱', thriving: '🌺' },
    },
  ],
  colors: {
    primary: '#E3350D',
    secondary: '#FF6B6B',
    accent: '#FFCB05',
    background: '#FFF5F5',
    surface: '#FFFFFF',
    text: '#1A1A2E',
    textSecondary: '#6B6B80',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#E3350D', '#FF6B6B'],
    tabBar: '#FFF0F0',
    tabBarActive: '#E3350D',
    tabBarInactive: '#C0A0A0',
    card: '#FFFFFF',
    border: '#F0D8D8',
  },
};

export const themes: AppTheme[] = [
  // Старшие
  csgoTheme,
  gotTheme,
  twilightTheme,
  animeTheme,
  // Младшие
  frozenTheme,
  minionsTheme,
  clashRoyaleTheme,
  pokemonTheme,
];

export const seniorThemes = themes.filter((t) => t.ageGroup === 'senior');
export const juniorThemes = themes.filter((t) => t.ageGroup === 'junior');

export const defaultTheme: AppTheme = csgoTheme;
