import { AppTheme } from '../types';

// ─── Старшие (8-11 класс) ────────────────────────────────────────

const csgoTheme: AppTheme = {
  id: 'csgo',
  name: 'CS:GO',
  emoji: '🔫',
  ageGroup: 'senior',
  backgroundEmojis: ['🔫', '💣', '🎯', '⚔️', '🛡️', '💥'],
  characters: [
    {
      id: 'csgo-ct',
      name: 'Контр-террорист',
      emoji: '🛡️',
      mascotEmojis: { sick: '💀', sad: '😰', neutral: '🛡️', happy: '😎', thriving: '🏆' },
    },
    {
      id: 'csgo-t',
      name: 'Террорист',
      emoji: '💣',
      mascotEmojis: { sick: '💀', sad: '😤', neutral: '💣', happy: '🔥', thriving: '⚡' },
    },
    {
      id: 'csgo-awp',
      name: 'AWPер',
      emoji: '🎯',
      mascotEmojis: { sick: '💀', sad: '😓', neutral: '🎯', happy: '🔫', thriving: '👑' },
    },
    {
      id: 'csgo-spec',
      name: 'Спецназ',
      emoji: '⚔️',
      mascotEmojis: { sick: '💀', sad: '😣', neutral: '⚔️', happy: '💪', thriving: '🦾' },
    },
  ],
  colors: {
    primary: '#E87B35',
    secondary: '#F5A623',
    accent: '#FF6B00',
    background: '#1A1A1A',
    surface: '#2A2A2A',
    text: '#F0E6D8',
    textSecondary: '#9A9080',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#E87B35', '#C75B20'],
    tabBar: '#1E1E1E',
    tabBarActive: '#F5A623',
    tabBarInactive: '#6B6358',
    card: '#2E2E2E',
    border: '#3D3830',
  },
};

const gotTheme: AppTheme = {
  id: 'got',
  name: 'Игра Престолов',
  emoji: '🐉',
  ageGroup: 'senior',
  backgroundEmojis: ['🐉', '⚔️', '🛡️', '👑', '🏰', '🗡️'],
  characters: [
    {
      id: 'got-dragon',
      name: 'Дракон',
      emoji: '🐉',
      mascotEmojis: { sick: '🥀', sad: '😔', neutral: '🐉', happy: '🔥', thriving: '👑' },
    },
    {
      id: 'got-wolf',
      name: 'Волк',
      emoji: '🐺',
      mascotEmojis: { sick: '🤕', sad: '🌧️', neutral: '🐺', happy: '🌙', thriving: '❄️' },
    },
    {
      id: 'got-lion',
      name: 'Лев',
      emoji: '🦁',
      mascotEmojis: { sick: '😵', sad: '😠', neutral: '🦁', happy: '💰', thriving: '⚔️' },
    },
    {
      id: 'got-raven',
      name: 'Ворон',
      emoji: '🐦‍⬛',
      mascotEmojis: { sick: '💀', sad: '🌑', neutral: '🐦‍⬛', happy: '🔮', thriving: '👁️' },
    },
  ],
  colors: {
    primary: '#C9A84C',
    secondary: '#E8D282',
    accent: '#8B0000',
    background: '#121010',
    surface: '#1E1A18',
    text: '#F0E8D8',
    textSecondary: '#A09882',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#8B0000', '#C9A84C'],
    tabBar: '#161212',
    tabBarActive: '#C9A84C',
    tabBarInactive: '#6B6050',
    card: '#252020',
    border: '#3A3028',
  },
};

const twilightTheme: AppTheme = {
  id: 'twilight',
  name: 'Сумерки',
  emoji: '🧛',
  ageGroup: 'senior',
  backgroundEmojis: ['🧛', '🐺', '🌙', '🦇', '🩸', '🔮'],
  characters: [
    {
      id: 'tw-vampire',
      name: 'Вампир',
      emoji: '🧛',
      mascotEmojis: { sick: '💀', sad: '🌑', neutral: '🧛', happy: '🩸', thriving: '⚡' },
    },
    {
      id: 'tw-werewolf',
      name: 'Оборотень',
      emoji: '🐺',
      mascotEmojis: { sick: '🤒', sad: '😢', neutral: '🐺', happy: '🌕', thriving: '💪' },
    },
    {
      id: 'tw-shewolf',
      name: 'Волчица',
      emoji: '🌙',
      mascotEmojis: { sick: '😷', sad: '😿', neutral: '🌙', happy: '✨', thriving: '🌟' },
    },
    {
      id: 'tw-mystic',
      name: 'Мистик',
      emoji: '🔮',
      mascotEmojis: { sick: '😵‍💫', sad: '😶‍🌫️', neutral: '🔮', happy: '🌌', thriving: '🌠' },
    },
  ],
  colors: {
    primary: '#8B0A1A',
    secondary: '#C0C0C0',
    accent: '#6B2D5B',
    background: '#0D0D12',
    surface: '#1A1820',
    text: '#E8E0F0',
    textSecondary: '#8A82A0',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#4A0E2C', '#8B0A1A'],
    tabBar: '#111018',
    tabBarActive: '#C0C0C0',
    tabBarInactive: '#5A5270',
    card: '#201C28',
    border: '#302838',
  },
};

const animeTheme: AppTheme = {
  id: 'anime',
  name: 'Аниме',
  emoji: '⛩️',
  ageGroup: 'senior',
  backgroundEmojis: ['🍥', '⛩️', '🌸', '✨', '💮', '🥷'],
  characters: [
    {
      id: 'anime-naruto',
      name: 'Наруто',
      emoji: '🍥',
      mascotEmojis: { sick: '😵', sad: '😤', neutral: '🍥', happy: '💪', thriving: '🌀' },
    },
    {
      id: 'anime-ninja',
      name: 'Ниндзя',
      emoji: '🥷',
      mascotEmojis: { sick: '🤕', sad: '😶', neutral: '🥷', happy: '⚡', thriving: '🔥' },
    },
    {
      id: 'anime-sakura',
      name: 'Сакура',
      emoji: '🌸',
      mascotEmojis: { sick: '🥀', sad: '😢', neutral: '🌸', happy: '💮', thriving: '✨' },
    },
    {
      id: 'anime-sensei',
      name: 'Сенсей',
      emoji: '📖',
      mascotEmojis: { sick: '😷', sad: '😑', neutral: '📖', happy: '🎓', thriving: '👑' },
    },
  ],
  colors: {
    primary: '#C850C0',
    secondary: '#FF6B9D',
    accent: '#7B2FBE',
    background: '#140818',
    surface: '#1E1025',
    text: '#F8E8FF',
    textSecondary: '#A888C0',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#7B2FBE', '#C850C0'],
    tabBar: '#180C20',
    tabBarActive: '#FF6B9D',
    tabBarInactive: '#6A4880',
    card: '#261830',
    border: '#382548',
  },
};

const sakuraTheme: AppTheme = {
  id: 'sakura',
  name: 'Сакура',
  emoji: '🌸',
  ageGroup: 'senior',
  backgroundEmojis: ['🌸', '🏯', '🎎', '🍡', '🎐', '🌺'],
  characters: [
    {
      id: 'sk-hanami',
      name: 'Ханами',
      emoji: '🌸',
      mascotEmojis: { sick: '🥀', sad: '😢', neutral: '🌸', happy: '💮', thriving: '✨' },
    },
    {
      id: 'sk-samurai',
      name: 'Самурай',
      emoji: '⚔️',
      mascotEmojis: { sick: '🤕', sad: '😔', neutral: '⚔️', happy: '🎌', thriving: '🏯' },
    },
    {
      id: 'sk-geisha',
      name: 'Гейша',
      emoji: '🎎',
      mascotEmojis: { sick: '😷', sad: '😿', neutral: '🎎', happy: '🌺', thriving: '👘' },
    },
    {
      id: 'sk-kitsune',
      name: 'Кицунэ',
      emoji: '🦊',
      mascotEmojis: { sick: '😵', sad: '😥', neutral: '🦊', happy: '🔮', thriving: '🌙' },
    },
  ],
  colors: {
    primary: '#E8A0BF',
    secondary: '#F2C6DE',
    accent: '#D45D8A',
    background: '#FFF5F9',
    surface: '#FFFFFF',
    text: '#3A1A2A',
    textSecondary: '#8A6078',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#E8A0BF', '#F2C6DE'],
    tabBar: '#FFF0F5',
    tabBarActive: '#D45D8A',
    tabBarInactive: '#C8A0B8',
    card: '#FFFFFF',
    border: '#F0D8E8',
  },
};

const gagarinTheme: AppTheme = {
  id: 'gagarin',
  name: 'Гагарин',
  emoji: '🚀',
  ageGroup: 'senior',
  backgroundEmojis: ['🚀', '🪐', '⭐', '🌌', '🛸', '☄️'],
  characters: [
    {
      id: 'gg-cosmonaut',
      name: 'Космонавт',
      emoji: '🧑‍🚀',
      mascotEmojis: { sick: '😵‍💫', sad: '😰', neutral: '🧑‍🚀', happy: '🚀', thriving: '🌟' },
    },
    {
      id: 'gg-rocket',
      name: 'Ракета',
      emoji: '🚀',
      mascotEmojis: { sick: '💨', sad: '😔', neutral: '🚀', happy: '🔥', thriving: '⭐' },
    },
    {
      id: 'gg-alien',
      name: 'Инопланетянин',
      emoji: '👽',
      mascotEmojis: { sick: '🤢', sad: '😕', neutral: '👽', happy: '🛸', thriving: '🌌' },
    },
    {
      id: 'gg-star',
      name: 'Звездочёт',
      emoji: '🔭',
      mascotEmojis: { sick: '😷', sad: '🌑', neutral: '🔭', happy: '🪐', thriving: '☄️' },
    },
  ],
  colors: {
    primary: '#6C5CE7',
    secondary: '#A29BFE',
    accent: '#0984E3',
    background: '#0A0A1E',
    surface: '#161640',
    text: '#E8E0FF',
    textSecondary: '#8A82B0',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#0A0A4A', '#6C5CE7'],
    tabBar: '#0E0E28',
    tabBarActive: '#A29BFE',
    tabBarInactive: '#4A4580',
    card: '#1E1E50',
    border: '#2A2A60',
  },
};

const marvelTheme: AppTheme = {
  id: 'marvel',
  name: 'Marvel',
  emoji: '🦸',
  ageGroup: 'senior',
  backgroundEmojis: ['🦸', '⚡', '🛡️', '🕷️', '🔨', '💥'],
  characters: [
    {
      id: 'mv-ironman',
      name: 'Железный человек',
      emoji: '🤖',
      mascotEmojis: { sick: '⚙️', sad: '😤', neutral: '🤖', happy: '🔥', thriving: '💎' },
    },
    {
      id: 'mv-spider',
      name: 'Паук',
      emoji: '🕷️',
      mascotEmojis: { sick: '🕸️', sad: '😟', neutral: '🕷️', happy: '🤸', thriving: '⚡' },
    },
    {
      id: 'mv-captain',
      name: 'Капитан',
      emoji: '🛡️',
      mascotEmojis: { sick: '🩹', sad: '😔', neutral: '🛡️', happy: '💪', thriving: '⭐' },
    },
    {
      id: 'mv-thor',
      name: 'Тор',
      emoji: '🔨',
      mascotEmojis: { sick: '😵', sad: '🌧️', neutral: '🔨', happy: '⚡', thriving: '👑' },
    },
  ],
  colors: {
    primary: '#E23636',
    secondary: '#518CCA',
    accent: '#F0141E',
    background: '#0C0C1A',
    surface: '#1A1A30',
    text: '#F0E8FF',
    textSecondary: '#8A88A0',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#E23636', '#518CCA'],
    tabBar: '#101020',
    tabBarActive: '#E23636',
    tabBarInactive: '#5A5878',
    card: '#202038',
    border: '#302E48',
  },
};

const onepieceTheme: AppTheme = {
  id: 'onepiece',
  name: 'One Piece',
  emoji: '☠️',
  ageGroup: 'senior',
  backgroundEmojis: ['☠️', '⛵', '🌊', '🏝️', '🗡️', '🍖'],
  characters: [
    {
      id: 'op-luffy',
      name: 'Луффи',
      emoji: '🏴‍☠️',
      mascotEmojis: { sick: '🤕', sad: '😤', neutral: '🏴‍☠️', happy: '🍖', thriving: '👑' },
    },
    {
      id: 'op-zoro',
      name: 'Зоро',
      emoji: '🗡️',
      mascotEmojis: { sick: '🩹', sad: '😑', neutral: '🗡️', happy: '⚔️', thriving: '🔥' },
    },
    {
      id: 'op-nami',
      name: 'Нами',
      emoji: '🗺️',
      mascotEmojis: { sick: '😷', sad: '😢', neutral: '🗺️', happy: '💰', thriving: '🌊' },
    },
    {
      id: 'op-chopper',
      name: 'Чоппер',
      emoji: '🦌',
      mascotEmojis: { sick: '🤒', sad: '😿', neutral: '🦌', happy: '💊', thriving: '⭐' },
    },
  ],
  colors: {
    primary: '#D4A843',
    secondary: '#F0D060',
    accent: '#2E5BA0',
    background: '#0E1428',
    surface: '#1A2440',
    text: '#F0E8D0',
    textSecondary: '#8A8878',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#2E5BA0', '#D4A843'],
    tabBar: '#121830',
    tabBarActive: '#D4A843',
    tabBarInactive: '#5A5870',
    card: '#1E2848',
    border: '#2A3458',
  },
};

// ─── Младшие (5-7 класс) ─────────────────────────────────────────

const frozenTheme: AppTheme = {
  id: 'frozen',
  name: 'Холодное сердце',
  emoji: '❄️',
  ageGroup: 'junior',
  backgroundEmojis: ['❄️', '⛄', '🌨️', '💎', '✨', '👸'],
  characters: [
    {
      id: 'fz-elsa',
      name: 'Эльза',
      emoji: '👸',
      mascotEmojis: { sick: '🥶', sad: '😢', neutral: '👸', happy: '❄️', thriving: '✨' },
    },
    {
      id: 'fz-olaf',
      name: 'Олаф',
      emoji: '⛄',
      mascotEmojis: { sick: '🫠', sad: '😥', neutral: '⛄', happy: '☀️', thriving: '🤗' },
    },
    {
      id: 'fz-anna',
      name: 'Анна',
      emoji: '👧',
      mascotEmojis: { sick: '🤒', sad: '😟', neutral: '👧', happy: '💕', thriving: '🌸' },
    },
    {
      id: 'fz-sven',
      name: 'Свен',
      emoji: '🦌',
      mascotEmojis: { sick: '🤕', sad: '😔', neutral: '🦌', happy: '🥕', thriving: '🎉' },
    },
  ],
  colors: {
    primary: '#5BA4CF',
    secondary: '#A3D5F7',
    accent: '#C4A8FF',
    background: '#E8F4FC',
    surface: '#FFFFFF',
    text: '#1A3A5C',
    textSecondary: '#6890B0',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#5BA4CF', '#A3D5F7'],
    tabBar: '#F0F8FF',
    tabBarActive: '#5BA4CF',
    tabBarInactive: '#98BEDD',
    card: '#FFFFFF',
    border: '#D0E8F8',
  },
};

const minionsTheme: AppTheme = {
  id: 'minions',
  name: 'Миньоны',
  emoji: '🍌',
  ageGroup: 'junior',
  backgroundEmojis: ['🍌', '😄', '🔧', '🧪', '🎸', '🦹'],
  characters: [
    {
      id: 'mn-bob',
      name: 'Боб',
      emoji: '🧸',
      mascotEmojis: { sick: '🤒', sad: '🥺', neutral: '🧸', happy: '😄', thriving: '🥳' },
    },
    {
      id: 'mn-kevin',
      name: 'Кевин',
      emoji: '🍌',
      mascotEmojis: { sick: '😷', sad: '😣', neutral: '🍌', happy: '😁', thriving: '🦸' },
    },
    {
      id: 'mn-stuart',
      name: 'Стюарт',
      emoji: '🎸',
      mascotEmojis: { sick: '🤕', sad: '😴', neutral: '🎸', happy: '🎶', thriving: '🤘' },
    },
    {
      id: 'mn-gru',
      name: 'Грю',
      emoji: '🦹',
      mascotEmojis: { sick: '😵', sad: '😤', neutral: '🦹', happy: '😏', thriving: '💎' },
    },
  ],
  colors: {
    primary: '#FFD02E',
    secondary: '#FEE680',
    accent: '#3D5FA0',
    background: '#FFF8E0',
    surface: '#FFFFFF',
    text: '#2A2A3C',
    textSecondary: '#7A7A90',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#FFD02E', '#FEB624'],
    tabBar: '#FFF8E8',
    tabBarActive: '#3D5FA0',
    tabBarInactive: '#B0B0C8',
    card: '#FFFFFF',
    border: '#F0E4C0',
  },
};

const clashRoyaleTheme: AppTheme = {
  id: 'clash',
  name: 'Clash Royale',
  emoji: '🏰',
  ageGroup: 'junior',
  backgroundEmojis: ['👑', '🏰', '⚔️', '🏹', '🐲', '⚡'],
  characters: [
    {
      id: 'cr-king',
      name: 'Король',
      emoji: '👑',
      mascotEmojis: { sick: '😵', sad: '😠', neutral: '👑', happy: '😤', thriving: '🏆' },
    },
    {
      id: 'cr-princess',
      name: 'Принцесса',
      emoji: '🏹',
      mascotEmojis: { sick: '🤕', sad: '😢', neutral: '🏹', happy: '🎯', thriving: '💫' },
    },
    {
      id: 'cr-knight',
      name: 'Рыцарь',
      emoji: '⚔️',
      mascotEmojis: { sick: '🩹', sad: '😔', neutral: '⚔️', happy: '🛡️', thriving: '💪' },
    },
    {
      id: 'cr-dragon',
      name: 'Дракон',
      emoji: '🐲',
      mascotEmojis: { sick: '😮‍💨', sad: '😕', neutral: '🐲', happy: '🔥', thriving: '⭐' },
    },
  ],
  colors: {
    primary: '#4A6FE0',
    secondary: '#7B9EF5',
    accent: '#9B59B6',
    background: '#0E1638',
    surface: '#182050',
    text: '#E8EEFF',
    textSecondary: '#8898CC',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#4A6FE0', '#9B59B6'],
    tabBar: '#121A40',
    tabBarActive: '#7B9EF5',
    tabBarInactive: '#4A5888',
    card: '#1E2860',
    border: '#283470',
  },
};

const pokemonTheme: AppTheme = {
  id: 'pokemon',
  name: 'Покемон',
  emoji: '⚡',
  ageGroup: 'junior',
  backgroundEmojis: ['⚡', '🔥', '💧', '🌿', '⭐', '🎯'],
  characters: [
    {
      id: 'pk-pikachu',
      name: 'Пикачу',
      emoji: '⚡',
      mascotEmojis: { sick: '😷', sad: '😢', neutral: '⚡', happy: '😊', thriving: '🌟' },
    },
    {
      id: 'pk-charmander',
      name: 'Чармандер',
      emoji: '🔥',
      mascotEmojis: { sick: '😮‍💨', sad: '😥', neutral: '🔥', happy: '😤', thriving: '🐉' },
    },
    {
      id: 'pk-squirtle',
      name: 'Сквиртл',
      emoji: '🐢',
      mascotEmojis: { sick: '🤒', sad: '😿', neutral: '🐢', happy: '💧', thriving: '🌊' },
    },
    {
      id: 'pk-bulbasaur',
      name: 'Бульбазавр',
      emoji: '🌿',
      mascotEmojis: { sick: '🥀', sad: '😔', neutral: '🌿', happy: '🌱', thriving: '🌺' },
    },
  ],
  colors: {
    primary: '#E3350D',
    secondary: '#FF6B6B',
    accent: '#FFCB05',
    background: '#FFF5F5',
    surface: '#FFFFFF',
    text: '#1A1A2E',
    textSecondary: '#6B6B80',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#E3350D', '#FF6B6B'],
    tabBar: '#FFF0F0',
    tabBarActive: '#E3350D',
    tabBarInactive: '#C0A0A0',
    card: '#FFFFFF',
    border: '#F0D8D8',
  },
};

const minecraftTheme: AppTheme = {
  id: 'minecraft',
  name: 'Minecraft',
  emoji: '⛏️',
  ageGroup: 'junior',
  backgroundEmojis: ['⛏️', '🟫', '🌳', '🧨', '🐷', '💎'],
  characters: [
    {
      id: 'mc-steve',
      name: 'Стив',
      emoji: '⛏️',
      mascotEmojis: { sick: '💀', sad: '😥', neutral: '⛏️', happy: '💎', thriving: '🏆' },
    },
    {
      id: 'mc-creeper',
      name: 'Крипер',
      emoji: '🧨',
      mascotEmojis: { sick: '😵', sad: '😔', neutral: '🧨', happy: '💥', thriving: '⚡' },
    },
    {
      id: 'mc-enderman',
      name: 'Эндермен',
      emoji: '👾',
      mascotEmojis: { sick: '😷', sad: '😶', neutral: '👾', happy: '🌀', thriving: '🌟' },
    },
    {
      id: 'mc-pig',
      name: 'Свинка',
      emoji: '🐷',
      mascotEmojis: { sick: '🤒', sad: '😿', neutral: '🐷', happy: '🥕', thriving: '🎉' },
    },
  ],
  colors: {
    primary: '#5D8C3E',
    secondary: '#8BC34A',
    accent: '#8B6914',
    background: '#F0F5E8',
    surface: '#FFFFFF',
    text: '#2A3018',
    textSecondary: '#6A7858',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#5D8C3E', '#8BC34A'],
    tabBar: '#E8F0E0',
    tabBarActive: '#5D8C3E',
    tabBarInactive: '#A0B090',
    card: '#FFFFFF',
    border: '#D0E0C0',
  },
};

const brawlTheme: AppTheme = {
  id: 'brawl',
  name: 'Brawl Stars',
  emoji: '💥',
  ageGroup: 'junior',
  backgroundEmojis: ['💥', '🌵', '🏆', '⭐', '💣', '🔥'],
  characters: [
    {
      id: 'bw-shelly',
      name: 'Шелли',
      emoji: '💥',
      mascotEmojis: { sick: '💀', sad: '😤', neutral: '💥', happy: '🔥', thriving: '🏆' },
    },
    {
      id: 'bw-colt',
      name: 'Кольт',
      emoji: '🔫',
      mascotEmojis: { sick: '🤕', sad: '😒', neutral: '🔫', happy: '😎', thriving: '⭐' },
    },
    {
      id: 'bw-spike',
      name: 'Спайк',
      emoji: '🌵',
      mascotEmojis: { sick: '🥀', sad: '😢', neutral: '🌵', happy: '😄', thriving: '🌟' },
    },
    {
      id: 'bw-crow',
      name: 'Ворон',
      emoji: '🐦‍⬛',
      mascotEmojis: { sick: '😵', sad: '😔', neutral: '🐦‍⬛', happy: '🗡️', thriving: '💎' },
    },
  ],
  colors: {
    primary: '#9B59B6',
    secondary: '#F1C40F',
    accent: '#E74C3C',
    background: '#1A0E28',
    surface: '#261840',
    text: '#F8E8FF',
    textSecondary: '#A088C0',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#9B59B6', '#F1C40F'],
    tabBar: '#1E1230',
    tabBarActive: '#F1C40F',
    tabBarInactive: '#6A4880',
    card: '#2E1E48',
    border: '#3A2858',
  },
};

const hogwartsTheme: AppTheme = {
  id: 'hogwarts',
  name: 'Хогвартс',
  emoji: '🧙',
  ageGroup: 'junior',
  backgroundEmojis: ['🧙', '🏰', '🦉', '🌙', '⚡', '📜'],
  characters: [
    {
      id: 'hw-wizard',
      name: 'Волшебник',
      emoji: '🧙',
      mascotEmojis: { sick: '🤒', sad: '😔', neutral: '🧙', happy: '⚡', thriving: '🌟' },
    },
    {
      id: 'hw-owl',
      name: 'Сова',
      emoji: '🦉',
      mascotEmojis: { sick: '😷', sad: '😿', neutral: '🦉', happy: '📜', thriving: '✨' },
    },
    {
      id: 'hw-witch',
      name: 'Ведьма',
      emoji: '🧹',
      mascotEmojis: { sick: '🥀', sad: '😢', neutral: '🧹', happy: '🔮', thriving: '💫' },
    },
    {
      id: 'hw-phoenix',
      name: 'Феникс',
      emoji: '🔥',
      mascotEmojis: { sick: '💀', sad: '😥', neutral: '🔥', happy: '🦅', thriving: '👑' },
    },
  ],
  colors: {
    primary: '#8B1A1A',
    secondary: '#D4A843',
    accent: '#7B3F00',
    background: '#120A0A',
    surface: '#1E1418',
    text: '#F0E0D0',
    textSecondary: '#A08878',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#8B1A1A', '#D4A843'],
    tabBar: '#160E0E',
    tabBarActive: '#D4A843',
    tabBarInactive: '#6A5848',
    card: '#261C20',
    border: '#382830',
  },
};

const amongusTheme: AppTheme = {
  id: 'amongus',
  name: 'Among Us',
  emoji: '👨‍🚀',
  ageGroup: 'junior',
  backgroundEmojis: ['👨‍🚀', '🛸', '🌍', '⭐', '🔧', '🗡️'],
  characters: [
    {
      id: 'au-red',
      name: 'Красный',
      emoji: '🔴',
      mascotEmojis: { sick: '💀', sad: '😰', neutral: '🔴', happy: '😎', thriving: '👑' },
    },
    {
      id: 'au-blue',
      name: 'Синий',
      emoji: '🔵',
      mascotEmojis: { sick: '😵', sad: '😢', neutral: '🔵', happy: '🔧', thriving: '⭐' },
    },
    {
      id: 'au-impostor',
      name: 'Импостор',
      emoji: '🗡️',
      mascotEmojis: { sick: '😷', sad: '😈', neutral: '🗡️', happy: '🔪', thriving: '💀' },
    },
    {
      id: 'au-green',
      name: 'Зелёный',
      emoji: '🟢',
      mascotEmojis: { sick: '🤒', sad: '😔', neutral: '🟢', happy: '🛸', thriving: '🌟' },
    },
  ],
  colors: {
    primary: '#C51111',
    secondary: '#4A4A6A',
    accent: '#1D1D3D',
    background: '#0A0A18',
    surface: '#161630',
    text: '#E0E0F0',
    textSecondary: '#8080A0',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#1D1D3D', '#C51111'],
    tabBar: '#0E0E20',
    tabBarActive: '#C51111',
    tabBarInactive: '#4A4A68',
    card: '#1C1C3A',
    border: '#2A2A4A',
  },
};

export const themes: AppTheme[] = [
  // Старшие
  csgoTheme,
  gotTheme,
  twilightTheme,
  animeTheme,
  sakuraTheme,
  gagarinTheme,
  marvelTheme,
  onepieceTheme,
  // Младшие
  frozenTheme,
  minionsTheme,
  clashRoyaleTheme,
  pokemonTheme,
  minecraftTheme,
  brawlTheme,
  hogwartsTheme,
  amongusTheme,
];

export const seniorThemes = themes.filter((t) => t.ageGroup === 'senior');
export const juniorThemes = themes.filter((t) => t.ageGroup === 'junior');

export const defaultTheme: AppTheme = csgoTheme;
