import { AppTheme } from '../types';

// ═══════════════════════════════════════════════════════════════════
// ─── Старшие (8-11 класс) — СВЕТЛЫЕ ─────────────────────────────
// ═══════════════════════════════════════════════════════════════════

const sakuraTheme: AppTheme = {
  id: 'sakura',
  name: 'Сакура',
  emoji: '🌸',
  ageGroup: 'senior',
  backgroundEmojis: ['🌸', '🏯', '🎎', '🍡', '🎐', '🌺'],
  colors: {
    primary: '#E8A0BF',
    secondary: '#F2C6DE',
    accent: '#D45D8A',
    background: '#FFF5F9',
    surface: '#FFFFFF',
    text: '#3A1A2A',
    textSecondary: '#8A6078',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#E8A0BF', '#F2C6DE'],
    tabBar: '#FFF0F5',
    tabBarActive: '#D45D8A',
    tabBarInactive: '#C8A0B8',
    card: '#FFFFFF',
    border: '#F0D8E8',
  },
};

const animeTheme: AppTheme = {
  id: 'anime',
  name: 'Аниме',
  emoji: '⛩️',
  ageGroup: 'senior',
  backgroundEmojis: ['🍥', '⛩️', '🌸', '✨', '💮', '🥷'],
  colors: {
    primary: '#C850C0',
    secondary: '#FF6B9D',
    accent: '#7B2FBE',
    background: '#FFF5FF',
    surface: '#FFFFFF',
    text: '#2A1A30',
    textSecondary: '#8A70A0',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#C850C0', '#FF6B9D'],
    tabBar: '#FFF0FA',
    tabBarActive: '#C850C0',
    tabBarInactive: '#C8A0D0',
    card: '#FFFFFF',
    border: '#F0D8F0',
  },
};

const marvelTheme: AppTheme = {
  id: 'marvel',
  name: 'Marvel',
  emoji: '🦸',
  ageGroup: 'senior',
  backgroundEmojis: ['🦸', '⚡', '🛡️', '🕷️', '🔨', '💥'],
  colors: {
    primary: '#E23636',
    secondary: '#518CCA',
    accent: '#F0141E',
    background: '#EEF4FF',
    surface: '#FFFFFF',
    text: '#1A1A30',
    textSecondary: '#6878A0',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#4088E0', '#518CCA'],
    tabBar: '#F0F4FF',
    tabBarActive: '#E23636',
    tabBarInactive: '#A0B0D0',
    card: '#FFFFFF',
    border: '#D0E0F8',
  },
};

const onepieceTheme: AppTheme = {
  id: 'onepiece',
  name: 'One Piece',
  emoji: '☠️',
  ageGroup: 'senior',
  backgroundEmojis: ['☠️', '⛵', '🌊', '🏝️', '🗡️', '🍖'],
  colors: {
    primary: '#D4A843',
    secondary: '#F0D060',
    accent: '#2E8BC0',
    background: '#F0F8FF',
    surface: '#FFFFFF',
    text: '#1A2840',
    textSecondary: '#6888A0',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#FFA850', '#60B8E8'],
    tabBar: '#F0F8FF',
    tabBarActive: '#D4A843',
    tabBarInactive: '#A0B8C8',
    card: '#FFFFFF',
    border: '#D0E4F0',
  },
};

const kpopTheme: AppTheme = {
  id: 'kpop',
  name: 'K-Pop',
  emoji: '🎤',
  ageGroup: 'senior',
  backgroundEmojis: ['🎤', '💜', '🎶', '✨', '💃', '🎧'],
  colors: {
    primary: '#C850C0',
    secondary: '#FF80C0',
    accent: '#00C9DB',
    background: '#FFF5FF',
    surface: '#FFFFFF',
    text: '#2A1A30',
    textSecondary: '#8870A0',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#C850C0', '#FF80C0'],
    tabBar: '#FFF0FA',
    tabBarActive: '#C850C0',
    tabBarInactive: '#C0A0C8',
    card: '#FFFFFF',
    border: '#F0D0F0',
  },
};

const genshinTheme: AppTheme = {
  id: 'genshin',
  name: 'Genshin Impact',
  emoji: '✨',
  ageGroup: 'senior',
  backgroundEmojis: ['✨', '⚡', '🌸', '🗡️', '🌟', '🔥'],
  colors: {
    primary: '#4878C8',
    secondary: '#80B0E8',
    accent: '#D4A843',
    background: '#F0F8FF',
    surface: '#FFFFFF',
    text: '#1A2840',
    textSecondary: '#6080A0',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#4878C8', '#80B0E8'],
    tabBar: '#F0F8FF',
    tabBarActive: '#4878C8',
    tabBarInactive: '#A0B8D0',
    card: '#FFFFFF',
    border: '#D0E0F0',
  },
};

// ─── Старшие (8-11 класс) — ТЁМНЫЕ ─────────────────────────────

const csgoTheme: AppTheme = {
  id: 'csgo',
  name: 'CS:GO',
  emoji: '🔫',
  ageGroup: 'senior',
  backgroundEmojis: ['🔫', '💣', '🎯', '⚔️', '🛡️', '💥'],
  colors: {
    primary: '#E87B35',
    secondary: '#F5A623',
    accent: '#FF6B00',
    background: '#1A1A1A',
    surface: '#2A2A2A',
    text: '#F0E6D8',
    textSecondary: '#9A9080',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#E87B35', '#C75B20'],
    tabBar: '#1E1E1E',
    tabBarActive: '#F5A623',
    tabBarInactive: '#6B6358',
    card: '#2E2E2E',
    border: '#3D3830',
  },
};

const gotTheme: AppTheme = {
  id: 'got',
  name: 'Игра Престолов',
  emoji: '🐉',
  ageGroup: 'senior',
  backgroundEmojis: ['🐉', '⚔️', '🛡️', '👑', '🏰', '🗡️'],
  colors: {
    primary: '#C9A84C',
    secondary: '#E8D282',
    accent: '#8B0000',
    background: '#121010',
    surface: '#1E1A18',
    text: '#F0E8D8',
    textSecondary: '#A09882',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#8B0000', '#C9A84C'],
    tabBar: '#161212',
    tabBarActive: '#C9A84C',
    tabBarInactive: '#6B6050',
    card: '#252020',
    border: '#3A3028',
  },
};

const twilightTheme: AppTheme = {
  id: 'twilight',
  name: 'Сумерки',
  emoji: '🧛',
  ageGroup: 'senior',
  backgroundEmojis: ['🧛', '🐺', '🌙', '🦇', '🩸', '🔮'],
  colors: {
    primary: '#8B0A1A',
    secondary: '#C0C0C0',
    accent: '#6B2D5B',
    background: '#0D0D12',
    surface: '#1A1820',
    text: '#E8E0F0',
    textSecondary: '#8A82A0',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#4A0E2C', '#8B0A1A'],
    tabBar: '#111018',
    tabBarActive: '#C0C0C0',
    tabBarInactive: '#5A5270',
    card: '#201C28',
    border: '#302838',
  },
};

const gagarinTheme: AppTheme = {
  id: 'gagarin',
  name: 'Гагарин',
  emoji: '🚀',
  ageGroup: 'senior',
  backgroundEmojis: ['🚀', '🪐', '⭐', '🌌', '🛸', '☄️'],
  colors: {
    primary: '#6C5CE7',
    secondary: '#A29BFE',
    accent: '#0984E3',
    background: '#0A0A1E',
    surface: '#161640',
    text: '#E8E0FF',
    textSecondary: '#8A82B0',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#0A0A4A', '#6C5CE7'],
    tabBar: '#0E0E28',
    tabBarActive: '#A29BFE',
    tabBarInactive: '#4A4580',
    card: '#1E1E50',
    border: '#2A2A60',
  },
};

const witcherTheme: AppTheme = {
  id: 'witcher',
  name: 'Ведьмак',
  emoji: '🐺',
  ageGroup: 'senior',
  backgroundEmojis: ['🐺', '⚔️', '🧪', '🔮', '🏰', '🌲'],
  colors: {
    primary: '#C0A060',
    secondary: '#E0C888',
    accent: '#8B0000',
    background: '#121010',
    surface: '#1E1A16',
    text: '#E8DCC8',
    textSecondary: '#A09878',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#8B0000', '#C0A060'],
    tabBar: '#161210',
    tabBarActive: '#C0A060',
    tabBarInactive: '#6B6048',
    card: '#252018',
    border: '#3A3020',
  },
};

const aotTheme: AppTheme = {
  id: 'aot',
  name: 'Атака Титанов',
  emoji: '⚔️',
  ageGroup: 'senior',
  backgroundEmojis: ['⚔️', '🛡️', '🏰', '💥', '🔥', '🦅'],
  colors: {
    primary: '#8B4513',
    secondary: '#C08050',
    accent: '#2E8B57',
    background: '#1A1010',
    surface: '#261A18',
    text: '#F0E0D0',
    textSecondary: '#A08868',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#8B4513', '#2E8B57'],
    tabBar: '#1E1410',
    tabBarActive: '#C08050',
    tabBarInactive: '#6A5840',
    card: '#2A2018',
    border: '#3A2C20',
  },
};

const valorantTheme: AppTheme = {
  id: 'valorant',
  name: 'Valorant',
  emoji: '🎯',
  ageGroup: 'senior',
  backgroundEmojis: ['🎯', '💨', '👁️', '📡', '🔥', '⚡'],
  colors: {
    primary: '#FF4655',
    secondary: '#FF8090',
    accent: '#0F1923',
    background: '#0E0E1A',
    surface: '#1A1A2E',
    text: '#ECE8E1',
    textSecondary: '#8A88A0',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#FF4655', '#0F1923'],
    tabBar: '#121220',
    tabBarActive: '#FF4655',
    tabBarInactive: '#5A5870',
    card: '#1E1E32',
    border: '#2E2E42',
  },
};

const strangerthingsTheme: AppTheme = {
  id: 'strangerthings',
  name: 'Странные дела',
  emoji: '🔦',
  ageGroup: 'senior',
  backgroundEmojis: ['🔦', '👾', '🎄', '🧇', '🚲', '🔮'],
  colors: {
    primary: '#C41E3A',
    secondary: '#E85050',
    accent: '#FF4040',
    background: '#0A0508',
    surface: '#1A0E14',
    text: '#F0E0E0',
    textSecondary: '#A08088',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#C41E3A', '#3A0A18'],
    tabBar: '#0E080C',
    tabBarActive: '#C41E3A',
    tabBarInactive: '#6A4858',
    card: '#221420',
    border: '#3A1828',
  },
};

const lotrTheme: AppTheme = {
  id: 'lotr',
  name: 'Властелин Колец',
  emoji: '💍',
  ageGroup: 'senior',
  backgroundEmojis: ['💍', '🧙', '🏹', '⛏️', '🌳', '🦅'],
  colors: {
    primary: '#C9A84C',
    secondary: '#A0C878',
    accent: '#2E5B1A',
    background: '#0D0D15',
    surface: '#1A1A25',
    text: '#E8E0D0',
    textSecondary: '#8A8878',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#2E5B1A', '#C9A84C'],
    tabBar: '#111118',
    tabBarActive: '#C9A84C',
    tabBarInactive: '#5A5848',
    card: '#1E1E28',
    border: '#2E2E38',
  },
};

// ═══════════════════════════════════════════════════════════════════
// ─── Младшие (5-7 класс) — СВЕТЛЫЕ ──────────────────────────────
// ═══════════════════════════════════════════════════════════════════

const frozenTheme: AppTheme = {
  id: 'frozen',
  name: 'Холодное сердце',
  emoji: '❄️',
  ageGroup: 'junior',
  backgroundEmojis: ['❄️', '⛄', '🌨️', '💎', '✨', '👸'],
  colors: {
    primary: '#5BA4CF',
    secondary: '#A3D5F7',
    accent: '#C4A8FF',
    background: '#E8F4FC',
    surface: '#FFFFFF',
    text: '#1A3A5C',
    textSecondary: '#6890B0',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#5BA4CF', '#A3D5F7'],
    tabBar: '#F0F8FF',
    tabBarActive: '#5BA4CF',
    tabBarInactive: '#98BEDD',
    card: '#FFFFFF',
    border: '#D0E8F8',
  },
};

const minionsTheme: AppTheme = {
  id: 'minions',
  name: 'Миньоны',
  emoji: '🍌',
  ageGroup: 'junior',
  backgroundEmojis: ['🍌', '😄', '🔧', '🧪', '🎸', '🦹'],
  colors: {
    primary: '#FFD02E',
    secondary: '#FEE680',
    accent: '#3D5FA0',
    background: '#FFF8E0',
    surface: '#FFFFFF',
    text: '#2A2A3C',
    textSecondary: '#7A7A90',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#FFD02E', '#FEB624'],
    tabBar: '#FFF8E8',
    tabBarActive: '#3D5FA0',
    tabBarInactive: '#B0B0C8',
    card: '#FFFFFF',
    border: '#F0E4C0',
  },
};

const pokemonTheme: AppTheme = {
  id: 'pokemon',
  name: 'Покемон',
  emoji: '⚡',
  ageGroup: 'junior',
  backgroundEmojis: ['⚡', '🔥', '💧', '🌿', '⭐', '🎯'],
  colors: {
    primary: '#E3350D',
    secondary: '#FF6B6B',
    accent: '#FFCB05',
    background: '#FFF5F5',
    surface: '#FFFFFF',
    text: '#1A1A2E',
    textSecondary: '#6B6B80',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#E3350D', '#FF6B6B'],
    tabBar: '#FFF0F0',
    tabBarActive: '#E3350D',
    tabBarInactive: '#C0A0A0',
    card: '#FFFFFF',
    border: '#F0D8D8',
  },
};

const minecraftTheme: AppTheme = {
  id: 'minecraft',
  name: 'Minecraft',
  emoji: '⛏️',
  ageGroup: 'junior',
  backgroundEmojis: ['⛏️', '🟫', '🌳', '🧨', '🐷', '💎'],
  colors: {
    primary: '#5D8C3E',
    secondary: '#8BC34A',
    accent: '#8B6914',
    background: '#F0F5E8',
    surface: '#FFFFFF',
    text: '#2A3018',
    textSecondary: '#6A7858',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#5D8C3E', '#8BC34A'],
    tabBar: '#E8F0E0',
    tabBarActive: '#5D8C3E',
    tabBarInactive: '#A0B090',
    card: '#FFFFFF',
    border: '#D0E0C0',
  },
};

const spongebobTheme: AppTheme = {
  id: 'spongebob',
  name: 'Губка Боб',
  emoji: '🧽',
  ageGroup: 'junior',
  backgroundEmojis: ['🧽', '⭐', '🎵', '🐿️', '🦑', '🍔'],
  colors: {
    primary: '#FFD700',
    secondary: '#FFEB60',
    accent: '#40B8E0',
    background: '#E8F8FF',
    surface: '#FFFFFF',
    text: '#1A2A3A',
    textSecondary: '#6080A0',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#40B8E0', '#FFD700'],
    tabBar: '#E8F4FF',
    tabBarActive: '#40B8E0',
    tabBarInactive: '#A0C0D8',
    card: '#FFFFFF',
    border: '#C8E4F0',
  },
};

const marioTheme: AppTheme = {
  id: 'mario',
  name: 'Марио',
  emoji: '🍄',
  ageGroup: 'junior',
  backgroundEmojis: ['🍄', '⭐', '💚', '👑', '🔥', '🐢'],
  colors: {
    primary: '#E03020',
    secondary: '#FF6050',
    accent: '#20A020',
    background: '#E8F4FF',
    surface: '#FFFFFF',
    text: '#1A1A30',
    textSecondary: '#607090',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#E03020', '#FF6050'],
    tabBar: '#E8F0FF',
    tabBarActive: '#E03020',
    tabBarInactive: '#A0B0C8',
    card: '#FFFFFF',
    border: '#D0E0F0',
  },
};

const robloxTheme: AppTheme = {
  id: 'roblox',
  name: 'Roblox',
  emoji: '🟩',
  ageGroup: 'junior',
  backgroundEmojis: ['🟩', '🔨', '👑', '🤖', '⭐', '🎮'],
  colors: {
    primary: '#E04040',
    secondary: '#FF7070',
    accent: '#40A040',
    background: '#E0F0FF',
    surface: '#FFFFFF',
    text: '#1A2030',
    textSecondary: '#607090',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#E04040', '#40A040'],
    tabBar: '#E8F4FF',
    tabBarActive: '#E04040',
    tabBarInactive: '#A0B0C8',
    card: '#FFFFFF',
    border: '#C8E0F0',
  },
};

const sonicTheme: AppTheme = {
  id: 'sonic',
  name: 'Sonic',
  emoji: '🦔',
  ageGroup: 'junior',
  backgroundEmojis: ['🦔', '💍', '⭐', '🦊', '💨', '🌀'],
  colors: {
    primary: '#1870D0',
    secondary: '#50A0F0',
    accent: '#FFD700',
    background: '#E0F4FF',
    surface: '#FFFFFF',
    text: '#0A1A30',
    textSecondary: '#507098',
    overdue: '#E04060',
    success: '#20B080',
    warning: '#E0A020',
    gradient: ['#1870D0', '#50A0F0'],
    tabBar: '#E0F0FF',
    tabBarActive: '#1870D0',
    tabBarInactive: '#90B8D8',
    card: '#FFFFFF',
    border: '#C0D8F0',
  },
};

// ─── Младшие (5-7 класс) — ТЁМНЫЕ ──────────────────────────────

const clashRoyaleTheme: AppTheme = {
  id: 'clash',
  name: 'Clash Royale',
  emoji: '🏰',
  ageGroup: 'junior',
  backgroundEmojis: ['👑', '🏰', '⚔️', '🏹', '🐲', '⚡'],
  colors: {
    primary: '#4A6FE0',
    secondary: '#7B9EF5',
    accent: '#9B59B6',
    background: '#0E1638',
    surface: '#182050',
    text: '#E8EEFF',
    textSecondary: '#8898CC',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#4A6FE0', '#9B59B6'],
    tabBar: '#121A40',
    tabBarActive: '#7B9EF5',
    tabBarInactive: '#4A5888',
    card: '#1E2860',
    border: '#283470',
  },
};

const brawlTheme: AppTheme = {
  id: 'brawl',
  name: 'Brawl Stars',
  emoji: '💥',
  ageGroup: 'junior',
  backgroundEmojis: ['💥', '🌵', '🏆', '⭐', '💣', '🔥'],
  colors: {
    primary: '#9B59B6',
    secondary: '#F1C40F',
    accent: '#E74C3C',
    background: '#1A0E28',
    surface: '#261840',
    text: '#F8E8FF',
    textSecondary: '#A088C0',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#9B59B6', '#F1C40F'],
    tabBar: '#1E1230',
    tabBarActive: '#F1C40F',
    tabBarInactive: '#6A4880',
    card: '#2E1E48',
    border: '#3A2858',
  },
};

const hogwartsTheme: AppTheme = {
  id: 'hogwarts',
  name: 'Хогвартс',
  emoji: '🧙',
  ageGroup: 'junior',
  backgroundEmojis: ['🧙', '🏰', '🦉', '🌙', '⚡', '📜'],
  colors: {
    primary: '#8B1A1A',
    secondary: '#D4A843',
    accent: '#7B3F00',
    background: '#120A0A',
    surface: '#1E1418',
    text: '#F0E0D0',
    textSecondary: '#A08878',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#8B1A1A', '#D4A843'],
    tabBar: '#160E0E',
    tabBarActive: '#D4A843',
    tabBarInactive: '#6A5848',
    card: '#261C20',
    border: '#382830',
  },
};

const amongusTheme: AppTheme = {
  id: 'amongus',
  name: 'Among Us',
  emoji: '👨‍🚀',
  ageGroup: 'junior',
  backgroundEmojis: ['👨‍🚀', '🛸', '🌍', '⭐', '🔧', '🗡️'],
  colors: {
    primary: '#C51111',
    secondary: '#4A4A6A',
    accent: '#1D1D3D',
    background: '#0A0A18',
    surface: '#161630',
    text: '#E0E0F0',
    textSecondary: '#8080A0',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#1D1D3D', '#C51111'],
    tabBar: '#0E0E20',
    tabBarActive: '#C51111',
    tabBarInactive: '#4A4A68',
    card: '#1C1C3A',
    border: '#2A2A4A',
  },
};

const gravityfallsTheme: AppTheme = {
  id: 'gravityfalls',
  name: 'Гравити Фолз',
  emoji: '📖',
  ageGroup: 'junior',
  backgroundEmojis: ['📖', '🔺', '🌲', '🌟', '🎩', '👁️'],
  colors: {
    primary: '#3AA850',
    secondary: '#60C870',
    accent: '#D4A843',
    background: '#0E1820',
    surface: '#182830',
    text: '#E0F0E8',
    textSecondary: '#80A890',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#3AA850', '#D4A843'],
    tabBar: '#121C24',
    tabBarActive: '#3AA850',
    tabBarInactive: '#4A6858',
    card: '#1C2C34',
    border: '#2A3C40',
  },
};

const fortniteTheme: AppTheme = {
  id: 'fortnite',
  name: 'Fortnite',
  emoji: '🪂',
  ageGroup: 'junior',
  backgroundEmojis: ['🪂', '🏆', '⚡', '🔫', '🌀', '🎯'],
  colors: {
    primary: '#9D4DFF',
    secondary: '#C080FF',
    accent: '#00D4FF',
    background: '#100A20',
    surface: '#1C1438',
    text: '#E8E0FF',
    textSecondary: '#9080B8',
    overdue: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    gradient: ['#9D4DFF', '#00D4FF'],
    tabBar: '#140E28',
    tabBarActive: '#9D4DFF',
    tabBarInactive: '#5A4880',
    card: '#221A40',
    border: '#302850',
  },
};

// ═══════════════════════════════════════════════════════════════════

export const themes: AppTheme[] = [
  // Старшие — светлые первыми
  sakuraTheme,
  animeTheme,
  marvelTheme,
  onepieceTheme,
  kpopTheme,
  genshinTheme,
  // Старшие — тёмные
  csgoTheme,
  gotTheme,
  twilightTheme,
  gagarinTheme,
  witcherTheme,
  aotTheme,
  valorantTheme,
  strangerthingsTheme,
  lotrTheme,
  // Младшие — светлые первыми
  frozenTheme,
  minionsTheme,
  pokemonTheme,
  minecraftTheme,
  spongebobTheme,
  marioTheme,
  robloxTheme,
  sonicTheme,
  // Младшие — тёмные
  clashRoyaleTheme,
  brawlTheme,
  hogwartsTheme,
  amongusTheme,
  gravityfallsTheme,
  fortniteTheme,
];

export const seniorThemes = themes.filter((t) => t.ageGroup === 'senior');
export const juniorThemes = themes.filter((t) => t.ageGroup === 'junior');

export const allCharacters: import('../types').ThemeCharacter[] = [
  // cat
  { id: 'pk-pikachu', name: 'Пикачу', emoji: '⚡', mascotEmojis: { sick: '😷', sad: '😢', neutral: '⚡', happy: '😊', thriving: '🌟' } },
  // warrior
  { id: 'sk-samurai', name: 'Самурай', emoji: '⚔️', mascotEmojis: { sick: '🤕', sad: '😔', neutral: '⚔️', happy: '🎌', thriving: '🏯' } },
  // fox
  { id: 'sk-kitsune', name: 'Кицунэ', emoji: '🦊', mascotEmojis: { sick: '😵', sad: '😥', neutral: '🦊', happy: '🔮', thriving: '🌙' } },
  // wizard
  { id: 'hw-wizard', name: 'Волшебник', emoji: '🧙', mascotEmojis: { sick: '🤒', sad: '😔', neutral: '🧙', happy: '⚡', thriving: '🌟' } },
  // dragon
  { id: 'got-dragon', name: 'Дрогон', emoji: '🐉', mascotEmojis: { sick: '🥀', sad: '😔', neutral: '🐉', happy: '🔥', thriving: '👑' } },
  // ninja
  { id: 'anime-naruto', name: 'Наруто', emoji: '🍥', mascotEmojis: { sick: '😵', sad: '😤', neutral: '🍥', happy: '💪', thriving: '🌀' } },
  // critter
  { id: 'gs-paimon', name: 'Паймон', emoji: '🌟', mascotEmojis: { sick: '😷', sad: '🥺', neutral: '🌟', happy: '🍖', thriving: '👑' } },
  // robot
  { id: 'mv-ironman', name: 'Железный человек', emoji: '🤖', mascotEmojis: { sick: '⚙️', sad: '😤', neutral: '🤖', happy: '🔥', thriving: '💎' } },
  // bear
  { id: 'op-chopper', name: 'Чоппер', emoji: '🦌', mascotEmojis: { sick: '🤒', sad: '😿', neutral: '🦌', happy: '💊', thriving: '⭐' } },
  // ghost
  { id: 'au-impostor', name: 'Импостор', emoji: '🗡️', mascotEmojis: { sick: '😷', sad: '😈', neutral: '🗡️', happy: '🔪', thriving: '💀' } },
  // alien
  { id: 'mc-enderman', name: 'Эндермен', emoji: '👾', mascotEmojis: { sick: '😷', sad: '😶', neutral: '👾', happy: '🌀', thriving: '🌟' } },
  // owl
  { id: 'hw-owl', name: 'Сова', emoji: '🦉', mascotEmojis: { sick: '😷', sad: '😿', neutral: '🦉', happy: '📜', thriving: '✨' } },
  // ── Roblox ──
  { id: 'rb-noob', name: 'Нубик', emoji: '🎮', mascotEmojis: { sick: '😵', sad: '😢', neutral: '🎮', happy: '🔨', thriving: '👑' } },
  // ── Stranger Things ──
  { id: 'st-eleven', name: 'Одиннадцать', emoji: '🔮', mascotEmojis: { sick: '🩸', sad: '😢', neutral: '🔮', happy: '🧇', thriving: '⚡' } },
  { id: 'st-demogorgon', name: 'Демогоргон', emoji: '👾', mascotEmojis: { sick: '🥀', sad: '😶', neutral: '👾', happy: '🔥', thriving: '💀' } },
  // ── Fortnite ──
  { id: 'fn-drift', name: 'Дрифт', emoji: '🎭', mascotEmojis: { sick: '😵', sad: '😔', neutral: '🎭', happy: '⚡', thriving: '🌀' } },
  { id: 'fn-peely', name: 'Пили', emoji: '🍌', mascotEmojis: { sick: '🤢', sad: '😢', neutral: '🍌', happy: '🎉', thriving: '🌟' } },
];

export const defaultTheme: AppTheme = sakuraTheme;
